{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # It's best practice to manage these values outside of version control,
  # for example using --set or a separate values file.
  # The values here are base64 encoded by the template function.
  DATABASE_HOST: {{ .Values.database.host | b64enc | quote }}
  DATABASE_NAME: {{ .Values.database.name | b64enc | quote }}
  DATABASE_USER: {{ .Values.database.user | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  REDIS_URL: {{ .Values.redisUrl | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.secret_key_base | b64enc | quote }}
{{- end }}